# GoReleaser configuration for Skyhook Explorer
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Build frontend before Go compilation (gets embedded)
    - sh -c "cd web && npm install && npm run build"
    - mkdir -p internal/static/dist
    - sh -c "cp -r web/dist/* internal/static/dist/"

builds:
  - id: explorer
    main: ./cmd/explorer
    binary: kubectl-explorer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: skyhook-io
    name: explorer
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## Skyhook Explorer v{{.Version}}

    Kubernetes cluster visualization and topology explorer.

    ### Installation

    **Homebrew:**
    ```bash
    brew tap skyhook-io/skyhook-cli
    brew install skyhook-explorer
    ```

    **Manual (macOS Apple Silicon):**
    ```bash
    curl -LO https://github.com/skyhook-io/explorer/releases/download/v{{.Version}}/explorer_{{.Version}}_darwin_arm64.tar.gz
    tar -xzf explorer_{{.Version}}_darwin_arm64.tar.gz
    sudo mv kubectl-explorer /usr/local/bin/
    ```

    **Manual (macOS Intel):**
    ```bash
    curl -LO https://github.com/skyhook-io/explorer/releases/download/v{{.Version}}/explorer_{{.Version}}_darwin_amd64.tar.gz
    tar -xzf explorer_{{.Version}}_darwin_amd64.tar.gz
    sudo mv kubectl-explorer /usr/local/bin/
    ```

    **Manual (Linux amd64):**
    ```bash
    curl -LO https://github.com/skyhook-io/explorer/releases/download/v{{.Version}}/explorer_{{.Version}}_linux_amd64.tar.gz
    tar -xzf explorer_{{.Version}}_linux_amd64.tar.gz
    sudo mv kubectl-explorer /usr/local/bin/
    ```

    Then run: `kubectl explorer` or `skyhook-explorer`

# Homebrew formula (publishes to skyhook-io/homebrew-skyhook-cli)
brews:
  - name: skyhook-explorer
    repository:
      owner: skyhook-io
      name: homebrew-skyhook-cli
    directory: Formula
    homepage: "https://github.com/skyhook-io/explorer"
    description: "Kubernetes cluster visualization and topology explorer"
    license: "Apache-2.0"
    install: |
      bin.install "kubectl-explorer"
      bin.install_symlink "kubectl-explorer" => "skyhook-explorer"
    test: |
      system "#{bin}/kubectl-explorer", "--version"
