package issues

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// CNPGCertExpiryLayout is Go's time.Time.String() layout, which is how the
// operator writes status.certificates.expirations.
const CNPGCertExpiryLayout = "2006-01-02 15:04:05.999999999 -0700 MST"

// ParseCNPGCertExpiry reads one status.certificates.expirations value. A
// monotonic-clock suffix ("m=+0.1") can follow Time.String(); it is dropped.
// ok is false when the value does not parse: the expiry is then unknown.

// A certificate past its expiry and one approaching it are separate reasons
// so a consumer can word them without reading the message.
const (
	ReasonCNPGCertificateExpiring = "CNPGCertificateExpiring"
	ReasonCNPGCertificateExpired  = "CNPGCertificateExpired"
)

func ParseCNPGCertExpiry(v string) (time.Time, bool) {
	v = strings.TrimSpace(v)
	if i := strings.Index(v, " m="); i >= 0 {
		v = v[:i]
	}
	if v == "" {
		return time.Time{}, false
	}
	t, err := time.Parse(CNPGCertExpiryLayout, v)
	if err != nil {
		return time.Time{}, false
	}
	return t, true
}

// CNPGUserCertificateSecrets returns the Secrets a Cluster names in
// spec.certificates: their owner renews them. Every other Secret listed in
// status.certificates.expirations was generated by the operator, which renews
// it itself before expiry.
func CNPGUserCertificateSecrets(u *unstructured.Unstructured) map[string]string {
	out := map[string]string{}
	for _, f := range []string{"serverCASecret", "serverTLSSecret", "replicationTLSSecret", "clientCASecret"} {
		if name, _, _ := unstructured.NestedString(u.Object, "spec", "certificates", f); name != "" {
			if prev, ok := out[name]; ok {
				out[name] = prev + "," + f
			} else {
				out[name] = f
			}
		}
	}
	return out
}

const (
	cnpgCertWarnWithin     = 30 * 24 * time.Hour
	cnpgCertCriticalWithin = 7 * 24 * time.Hour
	// The operator renews its own certificates when they are within its
	// expiring threshold (7 days by default, EXPIRING_CHECK_THRESHOLD). An
	// operator-managed certificate this close to expiry means renewal has not
	// happened; before that point it is routine and raising it would light
	// every cluster for a third of each 90-day certificate lifetime.
	cnpgOperatorCertOverdueWithin = 24 * time.Hour
)

// detectCNPGCertificateIssues reports certificates close to expiry. One issue
// per Secret, so two expiring certificates stay two causes.
func detectCNPGCertificateIssues(gvr schema.GroupVersionResource, kind string, u *unstructured.Unstructured, now time.Time) []Issue {
	exp, _, _ := unstructured.NestedStringMap(u.Object, "status", "certificates", "expirations")
	if len(exp) == 0 {
		return nil
	}
	user := CNPGUserCertificateSecrets(u)
	secrets := make([]string, 0, len(exp))
	for s := range exp {
		secrets = append(secrets, s)
	}
	sort.Strings(secrets)

	var out []Issue
	ns, name := u.GetNamespace(), u.GetName()
	for _, secret := range secrets {
		at, ok := ParseCNPGCertExpiry(exp[secret])
		if !ok {
			continue
		}
		left := at.Sub(now)
		_, userProvided := user[secret]
		var sev Severity
		var msg string
		reason := ReasonCNPGCertificateExpiring
		switch {
		case left <= 0:
			sev, reason = SeverityCritical, ReasonCNPGCertificateExpired
			msg = fmt.Sprintf("The certificate in Secret %s expired %s", secret, at.UTC().Format(time.RFC3339))
		case userProvided && left < cnpgCertCriticalWithin:
			sev = SeverityCritical
			msg = fmt.Sprintf("The certificate in Secret %s expires in %s (%s); its owner renews it, not the operator", secret, cnpgDaysLeft(left), at.UTC().Format(time.RFC3339))
		case userProvided && left < cnpgCertWarnWithin:
			sev = SeverityWarning
			msg = fmt.Sprintf("The certificate in Secret %s expires in %s (%s); its owner renews it, not the operator", secret, cnpgDaysLeft(left), at.UTC().Format(time.RFC3339))
		case !userProvided && left < cnpgOperatorCertOverdueWithin:
			sev = SeverityCritical
			msg = fmt.Sprintf("The operator-managed certificate in Secret %s expires in %s and has not been renewed", secret, cnpgDaysLeft(left))
		default:
			continue
		}
		out = append(out, newConditionIssue(gvr, kind, ns, name, sev,
			reason, msg, time.Time{}, false,
			// One fingerprint across both reasons: expiring and then expired is
			// the same finding growing worse, not a new one.
			"CNPGCertificateExpiring/"+secret, u.GetCreationTimestamp().Time))
	}
	return out
}

func cnpgDaysLeft(d time.Duration) string {
	if d < 24*time.Hour {
		h := int(d.Hours())
		if h < 1 {
			return "under an hour"
		}
		return fmt.Sprintf("%dh", h)
	}
	days := int(d.Hours() / 24)
	if days == 1 {
		return "1 day"
	}
	return fmt.Sprintf("%d days", days)
}
