package auth

import (
	"testing"
	"time"
)

func TestConfig_Enabled(t *testing.T) {
	tests := []struct {
		mode string
		want bool
	}{
		{"", false},
		{"none", false},
		{"proxy", true},
		{"oidc", true},
	}

	for _, tt := range tests {
		t.Run(tt.mode, func(t *testing.T) {
			cfg := Config{Mode: tt.mode}
			if cfg.Enabled() != tt.want {
				t.Errorf("Config{Mode: %q}.Enabled() = %v, want %v", tt.mode, cfg.Enabled(), tt.want)
			}
		})
	}
}

func TestConfig_Defaults(t *testing.T) {
	cfg := Config{Mode: "proxy"}
	cfg.Defaults()

	if cfg.CookieTTL != 24*time.Hour {
		t.Errorf("CookieTTL = %v, want 24h", cfg.CookieTTL)
	}
	if cfg.UserHeader != "X-Forwarded-User" {
		t.Errorf("UserHeader = %q, want %q", cfg.UserHeader, "X-Forwarded-User")
	}
	if cfg.GroupsHeader != "X-Forwarded-Groups" {
		t.Errorf("GroupsHeader = %q, want %q", cfg.GroupsHeader, "X-Forwarded-Groups")
	}
	if cfg.OIDCGroupsClaim != "groups" {
		t.Errorf("OIDCGroupsClaim = %q, want %q", cfg.OIDCGroupsClaim, "groups")
	}
	if cfg.Secret == "" {
		t.Error("Secret should be auto-generated when auth is enabled")
	}
}

func TestConfig_Defaults_NoSecretWhenDisabled(t *testing.T) {
	cfg := Config{Mode: "none"}
	cfg.Defaults()

	if cfg.Secret != "" {
		t.Error("Secret should not be auto-generated when auth is disabled")
	}
}

func TestConfig_Defaults_PreservesExistingValues(t *testing.T) {
	cfg := Config{
		Mode:            "proxy",
		Secret:          "my-secret",
		CookieTTL:       2 * time.Hour,
		UserHeader:      "X-Custom-User",
		GroupsHeader:    "X-Custom-Groups",
		OIDCGroupsClaim: "roles",
	}
	cfg.Defaults()

	if cfg.Secret != "my-secret" {
		t.Error("Defaults should not overwrite existing Secret")
	}
	if cfg.CookieTTL != 2*time.Hour {
		t.Error("Defaults should not overwrite existing CookieTTL")
	}
	if cfg.UserHeader != "X-Custom-User" {
		t.Error("Defaults should not overwrite existing UserHeader")
	}
	if cfg.GroupsHeader != "X-Custom-Groups" {
		t.Error("Defaults should not overwrite existing GroupsHeader")
	}
	if cfg.OIDCGroupsClaim != "roles" {
		t.Error("Defaults should not overwrite existing OIDCGroupsClaim")
	}
}

func TestConfig_Defaults_AutoGeneratedSecretUnique(t *testing.T) {
	cfg1 := Config{Mode: "proxy"}
	cfg1.Defaults()

	cfg2 := Config{Mode: "proxy"}
	cfg2.Defaults()

	if cfg1.Secret == cfg2.Secret {
		t.Error("Auto-generated secrets should be unique")
	}
}
