// Package ai drives a local agent CLI (Claude Code today) to investigate a
// Kubernetes resource, keyless on the user's own subscription, against Radar's
// own in-process MCP server.
//
// This is the OSS / local-first counterpart to Radar Hub's Cloud engine: the
// CLI IS the agent loop (tool-use + MCP + streaming), it runs on the user's
// machine against Radar's HTTP MCP endpoint (no tunnel, no token), and Radar
// never calls an LLM itself — the model auth lives entirely in the user's CLI.
//
// Security posture (see DiagnoseStream for the enforced flags):
//   - read-only: only the Radar MCP READ tools are pre-approved.
//   - no built-in tools: `--tools ""` disables Bash/Edit/Write/WebFetch/etc., so
//     an agent that ingests untrusted cluster logs can't be injected into running
//     shell commands or exfiltrating data over the network.
//   - scrubbed env + process-group kill + turn cap.
package ai

import (
	"bufio"
	"context"
	"crypto/rand"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/skyhook-io/radar/internal/investigationrefs"
	"github.com/skyhook-io/radar/pkg/investigation"
)

// ErrNoCLI means no usable agent CLI was found on PATH — the feature stays
// disabled (the HTTP layer returns 501) rather than failing per-request.
var ErrNoCLI = errors.New("no agent CLI available")

// Request is one investigation target (or a follow-up turn).
type Request struct {
	Kind      string
	Group     string
	Namespace string
	Name      string
	// MCPAddress is the locally dialable host:port of Radar's own MCP server.
	MCPAddress string
	// MCPBasePath is Radar's --base-path prefix ("" at the root). The MCP mounts
	// live under it, so the URL handed to the agent must carry it too.
	MCPBasePath string
	// EvidenceScope is a random per-turn correlation namespace generated by
	// RunManager. It is model-visible and is not an authenticator: Radar accepts
	// refs only when its private transport recorded their exact producer payload.
	EvidenceScope string
	// SessionID, when set, resumes a prior CLI session (multi-turn) so the agent
	// keeps full context (prior tool results + reasoning) without re-investigating.
	SessionID string
	// Question is the user's prompt for this turn. Empty on the first turn (we
	// auto-generate the investigate prompt); set for follow-ups.
	Question    string
	Explanation *Diagnosis
	// Verify marks a follow-up that was explicitly started to re-check the
	// resource after a change. It is replay metadata for the investigation UI;
	// the question remains the prompt sent to the agent.
	Verify bool
	// Apply, when true, runs a REMEDIATION turn: the agent is allowed the Radar
	// write tools and instructed to apply the fix it recommended. Gated entirely
	// by the caller (an explicit user confirmation) — the read-only investigation
	// path never sets this.
	Apply bool
	// Fix is the exact recommended-fix text the user saw and confirmed. On an
	// apply turn the agent is told to apply THIS specific change, so the operation
	// is bound to what was confirmed rather than the session's own recollection.
	Fix string
	// Agent selects which backend CLI drives this turn ("claude"/"codex"). Empty
	// uses the Diagnoser's default. A run picks once at Start and reuses it.
	Agent string
	// Profile is selected and validated before the run starts.
	Profile ExecutionProfile
	// Model optionally overrides the CLI's default model (e.g. "opus", "sonnet" for
	// Claude; a model slug for Codex). Empty leaves the agent's own default.
	Model string
	// Effort optionally sets the reasoning effort (Codex only: minimal/low/medium/
	// high). Empty leaves the default. Ignored by backends that don't support it.
	Effort string
	// Health is Radar's current server-side signal for the target at run start.
	// It frames the first prompt; follow-ups may still re-check live state.
	Health *ResourceHealthSignal
	// WorkDir is a stable per-run scratch directory the RunManager assigns (same
	// across the run's turns). Backends that need filesystem-scoped session state
	// use it (Cursor's --resume is workspace-scoped); others ignore it.
	WorkDir string
	// Metrics is the RunManager's probe of the metrics backend for this turn.
	// Only a confirmed connection reaches the prompt; the zero value says nothing.
	Metrics MetricsAvailability
}

// MetricsAvailability is the prompt's view of the metrics probe.
type MetricsAvailability = investigation.MetricsAvailability

// turnPrompt selects the prompt for a turn. Apply and explanation turns are
// exact scripts; read-only investigation turns (initial and follow-up) may
// additionally learn that metrics are available. OSS lets a revised
// assessment cite earlier turns of the run, which is what its binder proves.
func turnPrompt(req Request) string {
	target := investigation.Target{Kind: req.Kind, Group: req.Group, Namespace: req.Namespace, Name: req.Name}
	if req.Apply {
		return investigation.ApplyPrompt(target, req.Fix) // explicit, user-confirmed remediation turn
	}
	if req.Explanation != nil {
		return investigation.ExplanationPrompt(req.Explanation.Verdict)
	}
	opts := investigation.Options{Citations: investigation.CiteRun, Metrics: req.Metrics}
	switch {
	case strings.TrimSpace(req.Question) == "":
		return investigation.TaskPrompt(target, req.Health, opts)
	case req.Verify:
		return investigation.VerificationPrompt(req.Question, opts)
	default:
		return investigation.FollowUpPrompt(req.Question, opts)
	}
}

// ResourceHealthSignal is the health frame captured when a run starts; the
// contract package owns its shape because the prompt reads it.
type ResourceHealthSignal = investigation.HealthSignal

// HealthLine is one concrete issue/finding row on a ResourceHealthSignal.
type HealthLine = investigation.HealthLine

// Diagnosis is one turn's result: the contract verdict the page renders plus
// the CLI transport state that belongs to this run and never to the finding.
type Diagnosis struct {
	investigation.Verdict
	CostUSD *float64 `json:"costUsd"`
	Turns   int      `json:"turns"`
	// SessionID is the CLI session this turn ran in — pass it back as
	// Request.SessionID to continue the conversation.
	SessionID string `json:"sessionId"`
	// cliErrText preserves failures reported in a stream-json result instead of stderr.
	cliErrText string
	cliErrored bool
	// citations is untrusted model output. It never crosses the API boundary;
	// Run.finishTurn replaces it with server-authored provenance.
	citations     investigation.Citations
	evidenceScope string
	// issuedEvidence is a private snapshot from Radar's transport for this exact
	// turn. It is intentionally unexported and never serialized or model-authored.
	issuedEvidence investigationrefs.Records
}

// diagnosisFromText reads the CLI's final text through the contract parser.
func diagnosisFromText(text string) Diagnosis {
	parsed := investigation.Parse(text)
	return Diagnosis{Verdict: parsed.Verdict, citations: parsed.Citations}
}

// StreamEvent is one normalized event emitted during an investigation.
// "turn" marks the start of a new turn (carries Question/Apply) so a connecting
// or reconnecting client can reconstruct turn boundaries from the event log.
type StreamEvent struct {
	Type  string `json:"type"`            // "turn"|"phase"|"step"|"thinking"|"done"|"error"|"closed"
	Phase string `json:"phase,omitempty"` // "investigating"|"connected"|"ready"
	// Startup facts reported by the agent CLI on the "ready" phase: the model it
	// resolved, how many Radar tools it registered, and each MCP server's status.
	Model             string               `json:"model,omitempty"`
	ToolCount         *int                 `json:"toolCount,omitempty"`
	MCPServers        []MCPServerStatus    `json:"mcpServers,omitempty"`
	Step              *StepInfo            `json:"step,omitempty"`
	Token             string               `json:"token,omitempty"`
	Diag              *Diagnosis           `json:"diagnosis,omitempty"`
	Error             string               `json:"error,omitempty"`
	Question          string               `json:"question,omitempty"`          // on "turn"
	Apply             bool                 `json:"apply,omitempty"`             // on "turn"
	Verify            bool                 `json:"verify,omitempty"`            // on "turn"
	ExplainAssessment int                  `json:"explainAssessment,omitempty"` // sequence of the assessment's done event
	ApplyOutcome      ApplyMutationOutcome `json:"applyOutcome,omitempty"`      // on an apply turn's terminal event
	// VerificationScheduled closes the UI handoff between an apply terminal
	// event and its adjacent server-owned verification turn. It is durable so a
	// reconnect never has to infer scheduling from outcome text.
	VerificationScheduled bool `json:"verificationScheduled,omitempty"`
}

// ApplyMutationOutcome is Radar's evidence-backed view of a user-confirmed
// mutation attempt. It comes from terminal Radar write-tool results, never from
// the agent process exit code or its prose.
type ApplyMutationOutcome string

const (
	ApplyMutationConfirmed ApplyMutationOutcome = "confirmed"
	ApplyMutationFailed    ApplyMutationOutcome = "failed"
	ApplyMutationUnknown   ApplyMutationOutcome = "unknown"
)

// MCPServerStatus is one MCP server's connection state as the agent CLI
// reported it at startup. Only "connected" means the server's tools are usable.
type MCPServerStatus struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

// StepInfo describes one tool invocation (running → done).
type StepInfo struct {
	ID      string `json:"id"`
	Tool    string `json:"tool"`
	Status  string `json:"status"` // "running" | "done"
	Ms      *int64 `json:"ms,omitempty"`
	Summary string `json:"summary,omitempty"` // input args (on running)
	Result  string `json:"result,omitempty"`  // result text (on done), capped
	// EvidenceRef is generated by the private investigation MCP transport and
	// extracted by the agent adapter before Result is persisted. It lets the UI
	// verify assessment citations without exposing protocol markers as evidence.
	EvidenceRef string `json:"evidenceRef,omitempty"`
	// RadarEvidence is server-authored only after EvidenceRef and the adapter's
	// uncapped producer result match the active private transport ledger exactly,
	// and Result is verified as its capped derivative. Full-local agents can load
	// foreign MCP servers with colliding tool names, so a bare name is never
	// provenance.
	RadarEvidence bool `json:"radarEvidence,omitempty"`
	// IsError records the agent host's authoritative tool-result state. nil means
	// the host did not report a terminal state; false is a confirmed success.
	IsError *bool `json:"isError,omitempty"`
	// Truncated marks that Result was capped — so the UI tells the user the
	// payload (and anything they copy) is partial, not the complete tool output.
	Truncated bool `json:"truncated,omitempty"`
	// producerResult carries the clean, uncapped adapter result only until the
	// private evidence validator has compared it with the transport ledger. It is
	// unexported so it cannot enter the event log or wire response.
	producerResult *string
}

const defaultMaxTurns = 15

// agentCLICandidates are CLIs whose event stream we can parse + drive. Order is
// the default-selection preference when several are installed.
var agentCLICandidates = []string{"claude", "codex", "cursor-agent", "opencode"}

// Detector / Diagnoser ------------------------------------------------------

// ResolveCLI returns a usable agent-CLI path: the RADAR_AI_CLI_BIN override if
// set + present, else the first known candidate on PATH. "" if none.
func ResolveCLI() string {
	if explicit := strings.TrimSpace(os.Getenv("RADAR_AI_CLI_BIN")); explicit != "" {
		if p, err := exec.LookPath(explicit); err == nil {
			return p
		}
		return ""
	}
	for _, c := range agentCLICandidates {
		if p, err := exec.LookPath(c); err == nil {
			return p
		}
	}
	return ""
}

// Diagnoser drives one or more resolved agent CLIs via Agent backends (Claude,
// Codex, …). A run picks a backend by name; defName is used when none is given.
type Diagnoser struct {
	agents       map[string]Agent
	defName      string
	evidenceRefs *investigationrefs.Registry
}

func newDiagnoser(backends []Agent, evidenceRefs *investigationrefs.Registry) *Diagnoser {
	d := &Diagnoser{agents: map[string]Agent{}, evidenceRefs: evidenceRefs}
	for _, a := range backends {
		if d.defName == "" {
			d.defName = a.Name()
		}
		d.agents[a.Name()] = a
	}
	return d
}

// New returns a single-backend Diagnoser for the given binary, or ErrNoCLI if
// empty. The backend is chosen from the binary name (see resolveAgent). Used by
// the RADAR_AI_CLI_BIN override path and tests.
func New(bin string, evidenceRefs *investigationrefs.Registry) (*Diagnoser, error) {
	if strings.TrimSpace(bin) == "" {
		return nil, ErrNoCLI
	}
	sweepStaleMCPConfigs()
	return newDiagnoser([]Agent{resolveAgent(bin)}, evidenceRefs), nil
}

// NewDetected builds a Diagnoser over every supported agent CLI present on PATH.
// The RADAR_AI_CLI_BIN override, when set + present, forces a single backend.
// Returns ErrNoCLI when nothing usable is found.
func NewDetected(ctx context.Context, evidenceRefs *investigationrefs.Registry) (*Diagnoser, error) {
	if explicit := strings.TrimSpace(os.Getenv("RADAR_AI_CLI_BIN")); explicit != "" {
		return New(ResolveCLI(), evidenceRefs)
	}
	var backends []Agent
	for _, info := range DetectAgents(ctx, false) {
		if info.Supported {
			backends = append(backends, resolveAgent(info.Path))
		}
	}
	if len(backends) == 0 {
		return nil, ErrNoCLI
	}
	sweepStaleMCPConfigs()
	return newDiagnoser(backends, evidenceRefs), nil
}

// DefaultAgent is the backend chosen when a run doesn't name one.
func (d *Diagnoser) DefaultAgent() string { return d.defName }

// AgentInfos reports the exact backends this Diagnoser can drive.
func (d *Diagnoser) AgentInfos(ctx context.Context, withVersions bool) []AgentInfo {
	var infos []AgentInfo
	for _, name := range agentCLICandidates {
		agent, ok := d.agents[name]
		if !ok {
			continue
		}
		info := AgentInfo{
			Name:            name,
			Label:           AgentLabel(name),
			Path:            agent.Path(),
			Present:         true,
			Supported:       true,
			Profiles:        ProfilesFor(name),
			ConsentSurfaces: ConsentSurfacesFor(name),
		}
		if withVersions {
			info.Version = probeVersion(ctx, agent.Path())
		}
		infos = append(infos, info)
	}
	return infos
}

// AgentName normalizes a client-requested backend name to one that actually
// exists, falling back to the default — so a run records the agent it really used.
func (d *Diagnoser) AgentName(name string) string {
	if _, ok := d.agents[name]; ok {
		return name
	}
	return d.defName
}

// resolveTurnAgent picks the backend for a turn: the named one, else the default.
func (d *Diagnoser) resolveTurnAgent(name string) Agent {
	if a, ok := d.agents[name]; ok {
		return a
	}
	return d.agents[d.defName]
}

func maxTurns() int {
	if v := strings.TrimSpace(os.Getenv("RADAR_AI_MAX_TURNS")); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			return n
		}
	}
	return defaultMaxTurns
}

// DiagnoseStream spawns the CLI against Radar's local MCP and streams normalized
// events to onEvent, returning the assembled Diagnosis.
func (d *Diagnoser) DiagnoseStream(ctx context.Context, req Request, onEvent func(StreamEvent)) (Diagnosis, error) {
	if onEvent == nil {
		onEvent = func(StreamEvent) {}
	}
	if req.MCPAddress == "" {
		return Diagnosis{}, errors.New("ai: MCP address not set")
	}
	agent := d.resolveTurnAgent(req.Agent)
	if agent == nil {
		return Diagnosis{}, ErrNoCLI
	}
	profile := req.Profile
	if profile == "" {
		profile = DefaultProfileFor(agent.Name())
	}
	if !SupportsProfile(agent.Name(), profile) {
		return Diagnosis{}, fmt.Errorf("ai: %s does not support execution profile %q", AgentLabel(agent.Name()), profile)
	}

	// Read-only investigation turns get the private read-only MCP mount with
	// evidence correlation; an apply turn (user-confirmed) gets the ordinary full
	// mount with write tools and no investigation-only result markers.
	path := "/mcp"
	evidenceScope := ""
	var evidenceLease *investigationrefs.Scope
	if !req.Apply {
		if d.evidenceRefs == nil {
			return Diagnosis{}, errors.New("ai: investigation evidence registry not configured")
		}
		// The scope only correlates MCP calls with this turn; it is visible to the
		// model and therefore conveys no authority by itself. Begin activates a
		// bounded server-side issuance ledger before the agent can connect.
		evidenceScope = req.EvidenceScope
		if !investigation.ValidScope(evidenceScope) {
			evidenceScope = strings.ToLower(rand.Text())
		}
		var err error
		evidenceLease, err = d.evidenceRefs.Begin(evidenceScope)
		if err != nil {
			return Diagnosis{}, fmt.Errorf("ai: begin investigation evidence scope: %w", err)
		}
		defer evidenceLease.Close()
		path = "/mcp-investigation?scope=" + evidenceScope
	}
	mcpURL := fmt.Sprintf("http://%s%s%s", req.MCPAddress, req.MCPBasePath, path)

	// An apply turn runs in a FRESH session, not a resume: it acts only on the
	// user-confirmed fix text + target, so untrusted cluster data ingested during
	// the read-only investigation can't steer the write-enabled turn (injection).
	sessionID := req.SessionID
	if req.Apply {
		sessionID = ""
	}

	prompt := turnPrompt(req)
	sys := ""
	if sessionID == "" {
		sys = investigation.SystemPrompt // a fresh session establishes the SRE + security framing
	}

	cmd, cleanup, err := agent.command(ctx, turnSpec{
		mcpURL: mcpURL, prompt: prompt, systemPrompt: sys,
		sessionID: sessionID, apply: req.Apply, profile: profile,
		model: req.Model, effort: req.Effort, maxTurns: maxTurns(),
		workdir: req.WorkDir,
	})
	if err != nil {
		return Diagnosis{}, err
	}
	defer cleanup()

	// Process lifecycle is agent-agnostic. The platform helper kills the whole
	// process group/tree on cancel so no child agent process outlives the run.
	configureProcessLifecycle(cmd)
	cmd.WaitDelay = 5 * time.Second
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return Diagnosis{}, fmt.Errorf("ai: cli stdout: %w", err)
	}
	var stderr cappedBuffer
	stderr.limit = 8 << 10
	cmd.Stderr = &stderr
	if err := cmd.Start(); err != nil {
		return Diagnosis{}, fmt.Errorf("ai: start %s: %w", agent.Name(), err)
	}

	// The handshake watcher and the stream parser both report to the caller;
	// serialize them so callback consumers never see interleaved events.
	var emitMu sync.Mutex
	emit := func(event StreamEvent) {
		emitMu.Lock()
		defer emitMu.Unlock()
		onEvent(event)
	}
	emit(StreamEvent{Type: "phase", Phase: "investigating"})
	validator := investigationEvidenceValidator{
		registry: d.evidenceRefs,
		scope:    evidenceScope,
		claimed:  make(map[string]struct{}),
	}
	streamEvent := func(event StreamEvent) {
		emit(validator.validate(event))
	}
	streamDone := make(chan struct{})
	var handshake sync.WaitGroup
	if evidenceLease != nil {
		// The private mount marks the scope connected on the agent's MCP
		// handshake, which happens before its first message. Report it once.
		handshake.Add(1)
		go func() {
			defer handshake.Done()
			connected := evidenceLease.Connected()
			select {
			case <-connected:
			case <-streamDone:
				// Both may be ready when a short turn ends right after its
				// handshake; select picks arbitrarily, so re-check before giving up.
				select {
				case <-connected:
				default:
					return
				}
			}
			emit(StreamEvent{Type: "phase", Phase: "connected"})
		}()
	}
	diag := agent.parseStream(stdout, streamEvent)
	diag.evidenceScope = evidenceScope

	waitErr := cmd.Wait()
	// The watcher outlives stdout so a handshake that lands between EOF and
	// process exit is still reported, and always before this method returns.
	close(streamDone)
	handshake.Wait()
	if evidenceLease != nil {
		// Closing before the diagnosis leaves this method prevents any late private
		// MCP call from minting evidence for a completed turn. The deferred close
		// remains as the all-earlier-exits cleanup path.
		diag.issuedEvidence = evidenceLease.Close()
	}
	if waitErr != nil {
		if ctx.Err() != nil {
			return Diagnosis{}, ctx.Err()
		}
	}
	// A structured verdict wins over trailing process noise. Without one, either a
	// nonzero exit or an explicit stream error must remain a failed investigation.
	if !diag.Structured() && (waitErr != nil || diag.cliErrored) {
		return Diagnosis{}, agentExitError(
			agent.Name(), agent.SigninCmd(), diag.cliErrText, stderr.String(),
		)
	}
	return diag, nil
}

// MCP config / env / process helpers ----------------------------------------

func mcpConfigDir() string { return filepath.Join(os.TempDir(), "radar-ai-mcp") }

func sweepStaleMCPConfigs() {
	entries, err := os.ReadDir(mcpConfigDir())
	if err != nil {
		return
	}
	for _, e := range entries {
		_ = os.Remove(filepath.Join(mcpConfigDir(), e.Name()))
	}
}

// writeMCPConfig points the CLI at Radar's own local MCP. No auth header — the
// endpoint is loopback-only in standalone mode.
func writeMCPConfig(mcpURL string) (string, func(), error) {
	cfg := map[string]any{"mcpServers": map[string]any{"radar": map[string]any{
		"type": "http", "url": mcpURL,
	}}}
	b, err := json.Marshal(cfg)
	if err != nil {
		return "", func() {}, err
	}
	dir := mcpConfigDir()
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", func() {}, err
	}
	_ = os.Chmod(dir, 0o700)
	f, err := os.CreateTemp(dir, "mcp-*.json")
	if err != nil {
		return "", func() {}, err
	}
	if _, err := f.Write(b); err != nil {
		f.Close()
		os.Remove(f.Name())
		return "", func() {}, err
	}
	f.Close()
	return f.Name(), func() { os.Remove(f.Name()) }, nil
}

var (
	envAllowExact = map[string]bool{
		"PATH": true, "HOME": true, "USER": true, "LOGNAME": true,
		"LANG": true, "LC_ALL": true, "LC_CTYPE": true, "TZ": true,
		"TMPDIR": true, "SHELL": true, "SSL_CERT_FILE": true, "SSL_CERT_DIR": true,
		// AWS creds are passed through so BYO-Bedrock works; the user opted in.
		"AWS_PROFILE": true, "AWS_REGION": true, "AWS_DEFAULT_REGION": true,
	}
	envAllowPrefix = []string{"ANTHROPIC_", "CLAUDE_", "AWS_", "GOOGLE_", "CLOUD_ML_", "VERTEX_"}
)

// scrubbedEnv returns a minimal environment: the CLI ingests untrusted cluster
// data, so it shouldn't inherit unrelated host env. Provider-auth vars pass
// through so subscription / API-key / Bedrock / Vertex all work.
func scrubbedEnv() []string {
	var out []string
	for _, kv := range os.Environ() {
		k, _, ok := strings.Cut(kv, "=")
		if !ok {
			continue
		}
		if envAllowExact[k] {
			out = append(out, kv)
			continue
		}
		for _, p := range envAllowPrefix {
			if strings.HasPrefix(k, p) {
				out = append(out, kv)
				break
			}
		}
	}
	return out
}

type cappedBuffer struct {
	mu    sync.Mutex
	buf   strings.Builder
	limit int
}

func (c *cappedBuffer) Write(p []byte) (int, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if rem := c.limit - c.buf.Len(); rem > 0 {
		if len(p) > rem {
			c.buf.Write(p[:rem])
		} else {
			c.buf.Write(p)
		}
	}
	return len(p), nil
}

func (c *cappedBuffer) String() string {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.buf.String()
}

func formatExitDetails(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	if r := []rune(s); len(r) > 500 {
		s = string(r[:500]) + "…"
	}
	return ": " + s
}

// agentExitError classifies known failures and preserves both output channels for
// unknown ones, since CLIs disagree about where terminal errors are written.
func agentExitError(name, signinCmd, cliErrText, stderr string) error {
	details := strings.TrimSpace(cliErrText)
	cleanStderr := strings.TrimSpace(stderr)
	if cleanStderr != "" && cleanStderr != details {
		if details != "" {
			details += "\n"
		}
		details += cleanStderr
	}
	low := strings.ToLower(details)
	contains := func(subs ...string) bool {
		for _, s := range subs {
			if strings.Contains(low, s) {
				return true
			}
		}
		return false
	}
	switch {
	case contains("not logged in", "logged out", "not authenticated", "authentication required",
		"sign in required", "login required", "please log in", "/login"):
		return fmt.Errorf("%s isn't signed in. Run `%s` in a terminal to sign in, then try again%s", name, signinCmd, formatExitDetails(details))
	case contains("invalid api key", "no api key"):
		return fmt.Errorf("%s couldn't authenticate. Run `%s` to sign in, or check its API credentials, then try again%s", name, signinCmd, formatExitDetails(details))
	case contains("rate limit", "rate-limit", "429", "529", "quota", "overloaded", "too many requests"):
		return fmt.Errorf("%s is rate-limited or over quota. Wait a moment, then try again%s", name, formatExitDetails(details))
	case contains("max turns", "maximum turns", "turn limit", "error_max_turns"):
		return fmt.Errorf("%s hit its step limit before finishing. Try again, or ask a narrower follow-up%s", name, formatExitDetails(details))
	default:
		return fmt.Errorf("%s stopped unexpectedly%s", name, formatExitDetails(details))
	}
}

// stream-json parsing -------------------------------------------------------

type cliEvent struct {
	Type    string `json:"type"`
	Message *struct {
		Content []struct {
			Type      string          `json:"type"`
			Text      string          `json:"text"`
			Thinking  string          `json:"thinking"`
			ID        string          `json:"id"`
			Name      string          `json:"name"`
			Input     json.RawMessage `json:"input"`
			ToolUseID string          `json:"tool_use_id"`
			Content   json.RawMessage `json:"content"`
			IsError   bool            `json:"is_error"`
		} `json:"content"`
	} `json:"message"`
	Result       string   `json:"result"`
	Subtype      string   `json:"subtype"`
	IsError      bool     `json:"is_error"`
	TotalCostUSD *float64 `json:"total_cost_usd"`
	NumTurns     int      `json:"num_turns"`
	SessionID    string   `json:"session_id"`
	// system/init only.
	Model      string            `json:"model"`
	Tools      []string          `json:"tools"`
	MCPServers []MCPServerStatus `json:"mcp_servers"`
}

// agentReadyEvent reports the CLI's init message as a startup phase. Radar
// tools are counted by their MCP prefix so the count reflects what the model can
// actually call, not what Radar offered.
func agentReadyEvent(model string, tools []string, servers []MCPServerStatus) StreamEvent {
	count := 0
	for _, tool := range tools {
		if strings.HasPrefix(tool, "mcp__radar__") {
			count++
		}
	}
	return StreamEvent{
		Type: "phase", Phase: "ready",
		Model: model, ToolCount: &count, MCPServers: servers,
	}
}

func parseStream(r io.Reader, onEvent func(StreamEvent)) Diagnosis {
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 8<<20)
	starts := map[string]time.Time{}
	var finalText string
	var resultIsError bool
	var resultSubtype string
	var cost *float64
	var turns int
	var sessionID string

	// Claude streams its narration as standalone `text` messages interleaved with
	// tool calls. We surface ONLY the narration that directly precedes a tool call —
	// the "let me check the logs" lead-in to an action. We deliberately drop any text
	// that precedes another text, a thinking block, or the `result`: that trailing
	// prose is the model restating its conclusion (root cause / remediation) right
	// before the JSON report, and it would duplicate the structured result card. So
	// we hold the latest text and only flush it at a tool_use boundary.
	var pendingText string
	flushNarration := func() {
		if t := strings.TrimSpace(pendingText); t != "" {
			onEvent(StreamEvent{Type: "thinking", Token: t})
		}
		pendingText = ""
	}

	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || line[0] != '{' {
			continue
		}
		var ev cliEvent
		if json.Unmarshal([]byte(line), &ev) != nil {
			continue
		}
		switch ev.Type {
		case "system":
			if ev.Subtype == "init" {
				onEvent(agentReadyEvent(ev.Model, ev.Tools, ev.MCPServers))
			}
		case "assistant":
			if ev.Message == nil {
				continue
			}
			for _, b := range ev.Message.Content {
				switch b.Type {
				case "text":
					// Supersede any prior un-flushed narration: the prior text did NOT
					// precede a tool, so it's conclusion prose, not an action lead-in —
					// drop it and keep only the latest.
					pendingText = b.Text
				case "thinking":
					// Narration before a thinking block isn't an action lead-in.
					pendingText = ""
					if b.Thinking != "" {
						onEvent(StreamEvent{Type: "thinking", Token: b.Thinking})
					}
				case "tool_use":
					flushNarration() // interim narration precedes its tool call
					tool := strings.TrimPrefix(b.Name, "mcp__radar__")
					starts[b.ID] = time.Now()
					args, _ := capPayload(strings.TrimSpace(string(b.Input)))
					onEvent(StreamEvent{Type: "step", Step: &StepInfo{
						ID: b.ID, Tool: tool, Status: "running", Summary: args,
					}})
				}
			}
		case "user":
			if ev.Message == nil {
				continue
			}
			for _, b := range ev.Message.Content {
				if b.Type != "tool_result" {
					continue
				}
				var ms *int64
				if t0, ok := starts[b.ToolUseID]; ok {
					v := time.Since(t0).Milliseconds()
					ms = &v
				}
				resultText, evidenceRef := investigation.SplitRefMarker(
					claudeResultText(b.Content),
				)
				res, trunc := capPayload(resultText)
				isError := b.IsError
				onEvent(StreamEvent{Type: "step", Step: &StepInfo{
					ID: b.ToolUseID, Status: "done", Ms: ms, Result: res,
					EvidenceRef: evidenceRef, IsError: &isError, Truncated: trunc,
					producerResult: &resultText,
				}})
			}
		case "result":
			finalText = ev.Result
			resultIsError = ev.IsError
			resultSubtype = ev.Subtype
			cost = ev.TotalCostUSD
			turns = ev.NumTurns
			sessionID = ev.SessionID
		}
	}

	d := diagnosisFromText(finalText)
	d.CostUSD = cost
	d.Turns = turns
	d.SessionID = sessionID
	// A CLI that aborts (auth failure, rate limit, …) reports the reason via an
	// is_error result on stdout, not stderr. Keep that text so the exit-error
	// builder can turn it into an actionable message.
	if resultIsError {
		d.cliErrored = true
		d.cliErrText = strings.TrimSpace(finalText)
		if d.cliErrText == "" {
			d.cliErrText = strings.TrimSpace(resultSubtype)
		}
	}
	return d
}

// maxToolPayload caps a tool's input/result text held in the event log. The MCP
// diagnose producer can legitimately return a 32 KiB aggregate log bundle plus
// a guarded resource, context, events, and change metadata in one JSON envelope.
// Keep enough headroom for that bounded response while still preventing an
// unbounded tool result from entering retained history.
const maxToolPayload = 96 << 10

type investigationEvidenceValidator struct {
	registry *investigationrefs.Registry
	scope    string
	claimed  map[string]struct{}
}

// validate promotes an adapter-extracted marker to server-authored provenance
// only when it maps to the exact private-transport payload in the currently
// active turn. The first matching event owns a ref; a later foreign MCP call
// cannot replay a marker and payload it observed earlier in the conversation.
func (v *investigationEvidenceValidator) validate(event StreamEvent) StreamEvent {
	step := event.Step
	if step == nil {
		return event
	}
	producerResult := step.producerResult
	step.producerResult = nil
	// Never accept a provenance bit from an agent adapter or test fixture.
	step.RadarEvidence = false
	if event.Type != "step" || v.scope == "" || step.Status != "done" ||
		step.EvidenceRef == "" || producerResult == nil {
		return event
	}
	retainedResult, truncated := capPayload(*producerResult)
	if retainedResult != step.Result || truncated != step.Truncated {
		return event
	}
	if _, claimed := v.claimed[step.EvidenceRef]; claimed {
		return event
	}
	if !v.registry.Matches(v.scope, step.EvidenceRef, *producerResult) {
		return event
	}
	step.RadarEvidence = true
	v.claimed[step.EvidenceRef] = struct{}{}
	return event
}

func toolArgsText(raw json.RawMessage) string {
	s := strings.TrimSpace(string(raw))
	if s == "" || s == "null" || s == "{}" {
		return ""
	}
	args, _ := capPayload(s)
	return args
}

// capPayload truncates s to maxToolPayload runes, reporting whether it cut.
func capPayload(s string) (string, bool) {
	if r := []rune(s); len(r) > maxToolPayload {
		return string(r[:maxToolPayload]) + "\n…", true
	}
	return s, false
}

// claudeResultText extracts human-readable text from a Claude tool_result's
// content, which can be a plain JSON string ("crashloop"), an MCP content array
// ([{type:"text",text:…}]), or some other JSON value (returned as-is).
func claudeResultText(raw json.RawMessage) string {
	s := strings.TrimSpace(string(raw))
	if s == "" {
		return ""
	}
	switch s[0] {
	case '"':
		var str string
		if json.Unmarshal(raw, &str) == nil {
			return str
		}
	case '[':
		var parts []struct {
			Text string `json:"text"`
		}
		if json.Unmarshal(raw, &parts) == nil {
			var b strings.Builder
			for _, p := range parts {
				b.WriteString(p.Text)
			}
			if b.Len() > 0 {
				return b.String()
			}
		}
	}
	return s
}
